version: '3.5'

services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'postgis'
    ports:
        - 5432:5432